

const ELEMENT_404_INLINE_STYLE = "inline_style"
const ELEMENT_404_OUTLINE_STYLE = "outline_style"
const ELEMENT_404_STYLE_ARGS = "style_args"

const ELEMENT_404_STYLE_TAGS = [
    ELEMENT_404_INLINE_STYLE,
    ELEMENT_404_OUTLINE_STYLE,
    ELEMENT_404_STYLE_ARGS
]
const ELEMENT_404_NOT_LOCK = "not_lock_"
const  ELEMENT_404_FULL_RENDER = 'full_render_'
const ELEMENT_404_QUANTUM_RENDER = 'quantum_render_'
const ELEMENT_404_NUMBER = 'number'
const  ELEMENT_404_RENDER_TAGS = [
    ELEMENT_404_NOT_LOCK,
    ELEMENT_404_FULL_RENDER,
    ELEMENT_404_QUANTUM_RENDER
]
const  ELEMENT_404_EMPTY = ''

const ELEMENT_404_CHANGE = 'change';
const ELEMENT_404_NOT_LOCK_CHANGE = ELEMENT_404_NOT_LOCK + ELEMENT_404_CHANGE;
const  ELEMENT_404_VALUE = 'value';
const  ELEMENT_404_START_VALUE = 'start_value';
const ELEMENT_404_PREVENT_LOCKER  = 'prevent_locker';
const  ELEMENT_404_TAG = 'tag';
const  ELEMENT_404_BUTTON = 'button';
const ELEMENT_404_PREVENT_LOCK = true;
const  ELEMENT_404_RENDER_CHANGES ="render_change";
const ELEMENT_404_STRING="String";
const ELEMENT_404_ARRAY="Array";
const ELEMENT_404_OBJECT="Object";
const  ELEMENT_404_SELECTED = 'selected'
    //style render
const ELEMENT_404_STATE="state";
const ELEMENT_404_MERGE_IF="mergeIf";
const  ELEMENT_404_MEDIA="media";
const ELEMENT_404_IDENTIFIER_TAG="Element404Identifier";

const  ELEMENT_404_STYLE_KEYS_TO_IGNORE=[
    ELEMENT_404_MERGE_IF,
    ELEMENT_404_MEDIA,
    ELEMENT_404_IDENTIFIER_TAG
];

