

const ELEMENT_404_INLINE_STYLE = "inline_style"
const ELEMENT_404_OUTLINE_STYLE = "outline_style"
const ELEMENT_404_STYLE_ARGS = "style_args"

const ELEMENT_404_STYLE_TAGS = [
    ELEMENT_404_INLINE_STYLE,
    ELEMENT_404_OUTLINE_STYLE,
    ELEMENT_404_STYLE_ARGS
]
const ELEMENT_404_NOT_LOCK = "not_lock_"
const  ELEMENT_404_FULL_RENDER = 'full_render_'
const ELEMENT_404_SMART_RENDER = 'smart_render_'

const  ELEMENT_404_RENDER_TAGS = [
    ELEMENT_404_NOT_LOCK,
    ELEMENT_404_FULL_RENDER,
    ELEMENT_404_SMART_RENDER
]
const  ELEMENT_404_EMPTY = ''

const ELEMENT_404_CHANGE = 'change'
const  ELEMENT_404_VALUE = 'value'